spring:
  application:
    name: Stevens Euerka Server

server:
  port: 8056

eureka:
  environment: UAT
  instance:
      defaultZone: http://localhost:8056/eureka
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8056/eureka